version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: github-gg-db
    environment:
      POSTGRES_DB: github_gg
      POSTGRES_USER: github_gg_user
      POSTGRES_PASSWORD: github_gg_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U github_gg_user -d github_gg"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: 